services:
  app:
    container_name: Dash_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 7050:7050
    networks:
      - timescale_network
    depends_on:
      - database
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: web-docs
    restart: always
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
    networks:
        - timescale_network
  database:
      image: timescale/timescaledb-ha:pg16
      container_name: dev_timescaledb
      restart: always
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        TIMESCALEDB_TELEMETRY: off
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      networks:
        - timescale_network
  pgadmin:
      image: dpage/pgadmin4:4.23
      container_name: dev_pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
      ports:
        - ${PGADMIN_PORT}:80
      depends_on:
        - database
      networks:
        - timescale_network

networks:
  timescale_network: