services:
  app:
    container_name: Dash_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 7050:7050
    networks:
      - timescale_network
    depends_on:
      - database
    environment:
      # Add any necessary environment variables specific to your app
      - APP_ENV=production

  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: web-docs
    restart: always
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
    networks:
      - timescale_network

  database:
    image: timescale/timescaledb-ha:pg16
    container_name: dev_timescaledb
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - type: volume
        source: timescale_volume
        target: /var/lib/postgresql/data
        read_only: false
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - timescale_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: dev_pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - database
    networks:
      - timescale_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  timescale_network:

volumes:
  timescale_volume:
  pgadmin_data: