services:
  app:
    container_name: Dash_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8051:8051
    networks:
      - network 
networks:
  network:
    driver: bridge