services:
  database:
    image: timescale/timescaledb:latest-pg13
    container_name: timescaledb
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - timescale_network

networks:
  timescale_network: